stages:
  - build
  - deploy
# 构建
build-job:
  stage: build
  only:
    - master
  cache:
    untracked: true
  script:
    - ls 
    - dotnet restore
    - dotnet publish -o ./out -c Release
  artifacts:
    # 可以缓存在gitlab的流水线记录中，供直接下载
    expire_in: 30 days
    paths:
      - User.Api/out/
  tags:
    - 01-user-api-builder
# 发布正式
deploy-job:
  stage: deploy
  only:
    - master
  dependencies:
    - build-job  # 这里一定要依赖build-job，不然dockerfile里面的out目录无法使用
  script:
    - ls User.Api/out/
    - ls
    - docker ps
    - sh ./check-images.sh
    - docker build -t user-api .
    # 这里可以添加将生成好的image上传到dockerhub或者docker本地仓库
    
    ### 如果生成的镜像需要统一上传到仓库管理，则后面的逻辑可以分离到另外一个runner去执行
    # 这里可以添加从dockerhub或本地仓库拉取指定镜像
    - docker run -d --name user-api --link sqlserver:sqlserver -p 8080:80  user-api
  tags:
    - 01-user-api-deploy