web:
   image: 'gitlab/gitlab-ce:12.0.2-ce.0'
   restart: always
   hostname: '127.0.0.1'
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://127.0.0.1:80'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '8929:80'
   volumes:
     - 'D:/docker/gitlab/config:/etc/gitlab'
     - 'D:/docker/gitlab/logs:/var/log/gitlab'
     - 'D:/docker/gitlab/data:/var/opt'